name: Python package installation
run-name: Python package installation

on: [push]

jobs:
  build:
    strategy:
        matrix:
            os: [ubuntu-latest]
            # ,macos-latest, windows-latest]
            python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build package
        run: |
          uv build --wheel

      - name: Install package
        id: run
        run: |
          uv tool install ./dist/pip_help*.whl
        continue-on-error: true

      - name: Check run status
        if: ${{ matrix.os == 'ubuntu-latest' }}
        #  or ${{ matrix.os == 'macos-latest' }}
        run: |
          exit "${{ steps.run.outputs.status }}"

          
