name: Python package installation
run-name: Python package installation

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check installation across different Python versions
        uses: ./.github/actions/check_installation


          
