name: Publish python distribution to TestPyPI

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up UV
              uses: astral-sh/setup-uv@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version-file: .python-version

            - name: Build a binary wheel and a source tarball
              run: |
                  uv build --wheel .

            - name: Store the distribution
              uses: actions/upload-artifact@v4
              with:
                  path: dist/
            
    publish-to-test-pypi:
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: testpypi
            url: https://test.pypi.org/p/pip-help

        permissions:
            id-token: write

        steps:
            - name: Download distribution
              uses: actions/download-artifact@v4
              with:
                  name: pip_help-0.1.0-py3-none-any.whl
                  path: dist/

            - name: Publish to TestPyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                repository-url: https://test.pypi.org/legacy/